on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Configure Environment
      run: |
        echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties

    - name: Download & Install OpenCV
      run: |
        echo ">>> Downloading OpenCV..."
        wget -q https://github.com/opencv/opencv/releases/download/4.10.0/opencv-4.10.0-android-sdk.zip -O opencv.zip
        unzip -q opencv.zip
        
        echo ">>> Setting up JNI Libs (.so)..."
        mkdir -p android/app/src/main/jniLibs
        # Копируем нативные библиотеки
        cp -r OpenCV-android-sdk/sdk/native/libs/* android/app/src/main/jniLibs/
        
        echo ">>> Setting up Java Libs (Extracting from AAR)..."
        mkdir -p android/app/libs
        
        # 1. Ищем любой .aar файл в папке SDK
        AAR_FILE=$(find OpenCV-android-sdk -name "*.aar" | head -n 1)
        
        if [ -z "$AAR_FILE" ]; then
          echo "!!! ERROR: No .aar file found in SDK !!!"
          ls -R OpenCV-android-sdk
          exit 1
        fi
        
        echo ">>> Found AAR at: $AAR_FILE"
        
        # 2. Извлекаем classes.jar из AAR и сохраняем как opencv_java4.jar
        unzip -p "$AAR_FILE" classes.jar > android/app/libs/opencv_java4.jar
        
        if [ ! -s android/app/libs/opencv_java4.jar ]; then
             echo "!!! ERROR: Failed to extract classes.jar or file is empty !!!"
             exit 1
        fi
        
        echo ">>> Success! Verifying libs:"
        ls -l android/app/libs/

    - name: Build APK
      run: |
        flutter clean
        flutter build apk --debug --android-skip-build-dependency-validation --no-pub --verbose
