on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
    
    - name: Configure Environment
      run: |
        echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
        echo "sdk.dir=$ANDROID_SDK_ROOT" >> android/local.properties

    - name: Download & Install OpenCV
      run: |
        echo ">>> Downloading OpenCV..."
        wget -q https://github.com/opencv/opencv/releases/download/4.10.0/opencv-4.10.0-android-sdk.zip -O opencv.zip
        unzip -q opencv.zip
        
        echo ">>> Setting up JNI Libs (.so)..."
        mkdir -p android/app/src/main/jniLibs
        cp -r OpenCV-android-sdk/sdk/native/libs/* android/app/src/main/jniLibs/
        
        echo ">>> Setting up Java Libs (.jar)..."
        mkdir -p android/app/libs
        
        # Находим jar файл и сохраняем путь в переменную
        JAR_FILE=$(find OpenCV-android-sdk -name "opencv_java4.jar" | head -n 1)
        
        if [ -z "$JAR_FILE" ]; then
          echo "!!! ERROR: opencv_java4.jar NOT FOUND in extracted SDK !!!"
          find OpenCV-android-sdk -name "*.jar"
          exit 1
        fi
        
        echo ">>> Found jar at: $JAR_FILE"
        cp "$JAR_FILE" android/app/libs/opencv_java4.jar
        
        echo ">>> Verifying file existence:"
        ls -l android/app/libs/

    - name: Build APK
      run: |
        flutter clean
        flutter build apk --debug --android-skip-build-dependency-validation --no-pub --verbose
